/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareRouteImport } from './routes/care'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoneRouteImport } from './routes/done'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as ShareRouteImport } from './routes/share'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffPatientIdRouteImport } from './routes/staff.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPatientIdRoute = StaffPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRoute
  '/interview': typeof InterviewRoute
  '/language': typeof LanguageRoute
  '/papers': typeof PapersRoute
  '/share': typeof ShareRoute
  '/staff': typeof StaffRouteWithChildren
  '/summary': typeof SummaryRoute
  '/timeline': typeof TimelineRoute
  '/staff/$patientId': typeof StaffPatientIdRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRoute
  '/interview': typeof InterviewRoute
  '/language': typeof LanguageRoute
  '/papers': typeof PapersRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/timeline': typeof TimelineRoute
  '/staff/$patientId': typeof StaffPatientIdRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRoute
  '/interview': typeof InterviewRoute
  '/language': typeof LanguageRoute
  '/papers': typeof PapersRoute
  '/share': typeof ShareRoute
  '/staff': typeof StaffRouteWithChildren
  '/summary': typeof SummaryRoute
  '/timeline': typeof TimelineRoute
  '/staff/$patientId': typeof StaffPatientIdRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/consent'
    | '/dashboard'
    | '/done'
    | '/help'
    | '/identity'
    | '/interview'
    | '/language'
    | '/papers'
    | '/share'
    | '/staff'
    | '/summary'
    | '/timeline'
    | '/staff/$patientId'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/consent'
    | '/dashboard'
    | '/done'
    | '/help'
    | '/identity'
    | '/interview'
    | '/language'
    | '/papers'
    | '/share'
    | '/summary'
    | '/timeline'
    | '/staff/$patientId'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/care'
    | '/consent'
    | '/dashboard'
    | '/done'
    | '/help'
    | '/identity'
    | '/interview'
    | '/language'
    | '/papers'
    | '/share'
    | '/staff'
    | '/summary'
    | '/timeline'
    | '/staff/$patientId'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareRoute: typeof CareRoute
  ConsentRoute: typeof ConsentRoute
  DashboardRoute: typeof DashboardRoute
  DoneRoute: typeof DoneRoute
  HelpRoute: typeof HelpRoute
  IdentityRoute: typeof IdentityRoute
  InterviewRoute: typeof InterviewRoute
  LanguageRoute: typeof LanguageRoute
  PapersRoute: typeof PapersRoute
  ShareRoute: typeof ShareRoute
  StaffRoute: typeof StaffRouteWithChildren
  SummaryRoute: typeof SummaryRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$patientId': {
      id: '/staff/$patientId'
      path: '/$patientId'
      fullPath: '/staff/$patientId'
      preLoaderRoute: typeof StaffPatientIdRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffPatientIdRoute: typeof StaffPatientIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffPatientIdRoute: StaffPatientIdRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareRoute: CareRoute,
  ConsentRoute: ConsentRoute,
  DashboardRoute: DashboardRoute,
  DoneRoute: DoneRoute,
  HelpRoute: HelpRoute,
  IdentityRoute: IdentityRoute,
  InterviewRoute: InterviewRoute,
  LanguageRoute: LanguageRoute,
  PapersRoute: PapersRoute,
  ShareRoute: ShareRoute,
  StaffRoute: StaffRouteWithChildren,
  SummaryRoute: SummaryRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
