/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareRouteImport } from './routes/care'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoneRouteImport } from './routes/done'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as OcrLabRouteImport } from './routes/ocr-lab'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as ShareRouteImport } from './routes/share'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as IdentityAadhaarRouteImport } from './routes/identity.aadhaar'
import { Route as IdentityAbhaRouteImport } from './routes/identity.abha'
import { Route as IdentityLoginRouteImport } from './routes/identity.login'
import { Route as IdentityNewPatientRouteImport } from './routes/identity.new-patient'
import { Route as IdentityRegistrationRouteImport } from './routes/identity.registration'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffPatientIdRouteImport } from './routes/staff.$patientId'
import { Route as IdentityAadhaarScanRouteImport } from './routes/identity.aadhaar.scan'
import { Route as IdentityAbhaInputRouteImport } from './routes/identity.abha.input'
import { Route as IdentityNewPatientFormRouteImport } from './routes/identity.new-patient.form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneRoute = DoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrLabRoute = OcrLabRouteImport.update({
  id: '/ocr-lab',
  path: '/ocr-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityAadhaarRoute = IdentityAadhaarRouteImport.update({
  id: '/aadhaar',
  path: '/aadhaar',
  getParentRoute: () => IdentityRoute,
} as any)
const IdentityAbhaRoute = IdentityAbhaRouteImport.update({
  id: '/abha',
  path: '/abha',
  getParentRoute: () => IdentityRoute,
} as any)
const IdentityLoginRoute = IdentityLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => IdentityRoute,
} as any)
const IdentityNewPatientRoute = IdentityNewPatientRouteImport.update({
  id: '/new-patient',
  path: '/new-patient',
  getParentRoute: () => IdentityRoute,
} as any)
const IdentityRegistrationRoute = IdentityRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => IdentityRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPatientIdRoute = StaffPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => StaffRoute,
} as any)
const IdentityAadhaarScanRoute = IdentityAadhaarScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => IdentityAadhaarRoute,
} as any)
const IdentityAbhaInputRoute = IdentityAbhaInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => IdentityAbhaRoute,
} as any)
const IdentityNewPatientFormRoute = IdentityNewPatientFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => IdentityNewPatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRouteWithChildren
  '/interview': typeof InterviewRoute
  '/language': typeof LanguageRoute
  '/ocr-lab': typeof OcrLabRoute
  '/papers': typeof PapersRoute
  '/share': typeof ShareRoute
  '/staff': typeof StaffRouteWithChildren
  '/summary': typeof SummaryRoute
  '/timeline': typeof TimelineRoute
  '/identity/aadhaar': typeof IdentityAadhaarRouteWithChildren
  '/identity/abha': typeof IdentityAbhaRouteWithChildren
  '/identity/login': typeof IdentityLoginRoute
  '/identity/new-patient': typeof IdentityNewPatientRouteWithChildren
  '/identity/registration': typeof IdentityRegistrationRoute
  '/staff/$patientId': typeof StaffPatientIdRoute
  '/staff/': typeof StaffIndexRoute
  '/identity/aadhaar/scan': typeof IdentityAadhaarScanRoute
  '/identity/abha/input': typeof IdentityAbhaInputRoute
  '/identity/new-patient/form': typeof IdentityNewPatientFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRouteWithChildren
  '/interview': typeof InterviewRoute
  '/language': typeof LanguageRoute
  '/ocr-lab': typeof OcrLabRoute
  '/papers': typeof PapersRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/timeline': typeof TimelineRoute
  '/identity/aadhaar': typeof IdentityAadhaarRouteWithChildren
  '/identity/abha': typeof IdentityAbhaRouteWithChildren
  '/identity/login': typeof IdentityLoginRoute
  '/identity/new-patient': typeof IdentityNewPatientRouteWithChildren
  '/identity/registration': typeof IdentityRegistrationRoute
  '/staff/$patientId': typeof StaffPatientIdRoute
  '/staff': typeof StaffIndexRoute
  '/identity/aadhaar/scan': typeof IdentityAadhaarScanRoute
  '/identity/abha/input': typeof IdentityAbhaInputRoute
  '/identity/new-patient/form': typeof IdentityNewPatientFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care': typeof CareRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/done': typeof DoneRoute
  '/help': typeof HelpRoute
  '/identity': typeof IdentityRouteWithChildren
  '/interview': typeof InterviewRoute
  '/language': typeof LanguageRoute
  '/ocr-lab': typeof OcrLabRoute
  '/papers': typeof PapersRoute
  '/share': typeof ShareRoute
  '/staff': typeof StaffRouteWithChildren
  '/summary': typeof SummaryRoute
  '/timeline': typeof TimelineRoute
  '/identity/aadhaar': typeof IdentityAadhaarRouteWithChildren
  '/identity/abha': typeof IdentityAbhaRouteWithChildren
  '/identity/login': typeof IdentityLoginRoute
  '/identity/new-patient': typeof IdentityNewPatientRouteWithChildren
  '/identity/registration': typeof IdentityRegistrationRoute
  '/staff/$patientId': typeof StaffPatientIdRoute
  '/staff/': typeof StaffIndexRoute
  '/identity/aadhaar/scan': typeof IdentityAadhaarScanRoute
  '/identity/abha/input': typeof IdentityAbhaInputRoute
  '/identity/new-patient/form': typeof IdentityNewPatientFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/consent'
    | '/dashboard'
    | '/done'
    | '/help'
    | '/identity'
    | '/interview'
    | '/language'
    | '/ocr-lab'
    | '/papers'
    | '/share'
    | '/staff'
    | '/summary'
    | '/timeline'
    | '/identity/aadhaar'
    | '/identity/abha'
    | '/identity/login'
    | '/identity/new-patient'
    | '/identity/registration'
    | '/staff/$patientId'
    | '/staff/'
    | '/identity/aadhaar/scan'
    | '/identity/abha/input'
    | '/identity/new-patient/form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/consent'
    | '/dashboard'
    | '/done'
    | '/help'
    | '/identity'
    | '/interview'
    | '/language'
    | '/ocr-lab'
    | '/papers'
    | '/share'
    | '/summary'
    | '/timeline'
    | '/identity/aadhaar'
    | '/identity/abha'
    | '/identity/login'
    | '/identity/new-patient'
    | '/identity/registration'
    | '/staff/$patientId'
    | '/staff'
    | '/identity/aadhaar/scan'
    | '/identity/abha/input'
    | '/identity/new-patient/form'
  id:
    | '__root__'
    | '/'
    | '/care'
    | '/consent'
    | '/dashboard'
    | '/done'
    | '/help'
    | '/identity'
    | '/interview'
    | '/language'
    | '/ocr-lab'
    | '/papers'
    | '/share'
    | '/staff'
    | '/summary'
    | '/timeline'
    | '/identity/aadhaar'
    | '/identity/abha'
    | '/identity/login'
    | '/identity/new-patient'
    | '/identity/registration'
    | '/staff/$patientId'
    | '/staff/'
    | '/identity/aadhaar/scan'
    | '/identity/abha/input'
    | '/identity/new-patient/form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareRoute: typeof CareRoute
  ConsentRoute: typeof ConsentRoute
  DashboardRoute: typeof DashboardRoute
  DoneRoute: typeof DoneRoute
  HelpRoute: typeof HelpRoute
  IdentityRoute: typeof IdentityRouteWithChildren
  InterviewRoute: typeof InterviewRoute
  LanguageRoute: typeof LanguageRoute
  OcrLabRoute: typeof OcrLabRoute
  PapersRoute: typeof PapersRoute
  ShareRoute: typeof ShareRoute
  StaffRoute: typeof StaffRouteWithChildren
  SummaryRoute: typeof SummaryRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done': {
      id: '/done'
      path: '/done'
      fullPath: '/done'
      preLoaderRoute: typeof DoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-lab': {
      id: '/ocr-lab'
      path: '/ocr-lab'
      fullPath: '/ocr-lab'
      preLoaderRoute: typeof OcrLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/aadhaar': {
      id: '/identity/aadhaar'
      path: '/aadhaar'
      fullPath: '/identity/aadhaar'
      preLoaderRoute: typeof IdentityAadhaarRouteImport
      parentRoute: typeof IdentityRoute
    }
    '/identity/abha': {
      id: '/identity/abha'
      path: '/abha'
      fullPath: '/identity/abha'
      preLoaderRoute: typeof IdentityAbhaRouteImport
      parentRoute: typeof IdentityRoute
    }
    '/identity/login': {
      id: '/identity/login'
      path: '/login'
      fullPath: '/identity/login'
      preLoaderRoute: typeof IdentityLoginRouteImport
      parentRoute: typeof IdentityRoute
    }
    '/identity/new-patient': {
      id: '/identity/new-patient'
      path: '/new-patient'
      fullPath: '/identity/new-patient'
      preLoaderRoute: typeof IdentityNewPatientRouteImport
      parentRoute: typeof IdentityRoute
    }
    '/identity/registration': {
      id: '/identity/registration'
      path: '/registration'
      fullPath: '/identity/registration'
      preLoaderRoute: typeof IdentityRegistrationRouteImport
      parentRoute: typeof IdentityRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$patientId': {
      id: '/staff/$patientId'
      path: '/$patientId'
      fullPath: '/staff/$patientId'
      preLoaderRoute: typeof StaffPatientIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/identity/aadhaar/scan': {
      id: '/identity/aadhaar/scan'
      path: '/scan'
      fullPath: '/identity/aadhaar/scan'
      preLoaderRoute: typeof IdentityAadhaarScanRouteImport
      parentRoute: typeof IdentityAadhaarRoute
    }
    '/identity/abha/input': {
      id: '/identity/abha/input'
      path: '/input'
      fullPath: '/identity/abha/input'
      preLoaderRoute: typeof IdentityAbhaInputRouteImport
      parentRoute: typeof IdentityAbhaRoute
    }
    '/identity/new-patient/form': {
      id: '/identity/new-patient/form'
      path: '/form'
      fullPath: '/identity/new-patient/form'
      preLoaderRoute: typeof IdentityNewPatientFormRouteImport
      parentRoute: typeof IdentityNewPatientRoute
    }
  }
}

interface IdentityAadhaarRouteChildren {
  IdentityAadhaarScanRoute: typeof IdentityAadhaarScanRoute
}

const IdentityAadhaarRouteChildren: IdentityAadhaarRouteChildren = {
  IdentityAadhaarScanRoute: IdentityAadhaarScanRoute,
}

const IdentityAadhaarRouteWithChildren = IdentityAadhaarRoute._addFileChildren(
  IdentityAadhaarRouteChildren,
)

interface IdentityAbhaRouteChildren {
  IdentityAbhaInputRoute: typeof IdentityAbhaInputRoute
}

const IdentityAbhaRouteChildren: IdentityAbhaRouteChildren = {
  IdentityAbhaInputRoute: IdentityAbhaInputRoute,
}

const IdentityAbhaRouteWithChildren = IdentityAbhaRoute._addFileChildren(
  IdentityAbhaRouteChildren,
)

interface IdentityNewPatientRouteChildren {
  IdentityNewPatientFormRoute: typeof IdentityNewPatientFormRoute
}

const IdentityNewPatientRouteChildren: IdentityNewPatientRouteChildren = {
  IdentityNewPatientFormRoute: IdentityNewPatientFormRoute,
}

const IdentityNewPatientRouteWithChildren =
  IdentityNewPatientRoute._addFileChildren(IdentityNewPatientRouteChildren)

interface IdentityRouteChildren {
  IdentityAadhaarRoute: typeof IdentityAadhaarRouteWithChildren
  IdentityAbhaRoute: typeof IdentityAbhaRouteWithChildren
  IdentityLoginRoute: typeof IdentityLoginRoute
  IdentityNewPatientRoute: typeof IdentityNewPatientRouteWithChildren
  IdentityRegistrationRoute: typeof IdentityRegistrationRoute
}

const IdentityRouteChildren: IdentityRouteChildren = {
  IdentityAadhaarRoute: IdentityAadhaarRouteWithChildren,
  IdentityAbhaRoute: IdentityAbhaRouteWithChildren,
  IdentityLoginRoute: IdentityLoginRoute,
  IdentityNewPatientRoute: IdentityNewPatientRouteWithChildren,
  IdentityRegistrationRoute: IdentityRegistrationRoute,
}

const IdentityRouteWithChildren = IdentityRoute._addFileChildren(
  IdentityRouteChildren,
)

interface StaffRouteChildren {
  StaffPatientIdRoute: typeof StaffPatientIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffPatientIdRoute: StaffPatientIdRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareRoute: CareRoute,
  ConsentRoute: ConsentRoute,
  DashboardRoute: DashboardRoute,
  DoneRoute: DoneRoute,
  HelpRoute: HelpRoute,
  IdentityRoute: IdentityRouteWithChildren,
  InterviewRoute: InterviewRoute,
  LanguageRoute: LanguageRoute,
  OcrLabRoute: OcrLabRoute,
  PapersRoute: PapersRoute,
  ShareRoute: ShareRoute,
  StaffRoute: StaffRouteWithChildren,
  SummaryRoute: SummaryRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
